### ISSUE TITLE
NILMTK converter support?

### ISSUE THREAD

**Issue by levaphenyl** [Pecan-Street/DataPort-Examples#1]
The [NILMTK library](https://github.com/nilmtk/nilmtk) has an existing converter to transform the DataPort data into a `nilm-metadata`-compatible format.
However, their converter broke due to successive changes in the DataPort API.
Therefore, I wrote for myself a CSV-to-HDF converter to use DataPort data with NILMTK.

Are you interested in a PR with my converter?
Would you maintain it allowing the NILMTK developers to link this repository in their documentation?

**Comment by levaphenyl** [comment]
@SMock123 Any thoughts on this?

**Comment by SMock123** [comment]
@levaphenyl Oh my! I'm not sure how I completely missed this for 3 years. If there is still interest in this, I'd be happy to accept a PR with your converter and will keep this repo alive (and pay better attention to it!). Apologies for missing this.

**Comment by levaphenyl** [comment]
@SMock123  - Thank you for getting back on this! :) I finally merged my code in NILMTK through [this PR](https://github.com/nilmtk/nilmtk/pull/941).
I am closing this ticket. Please, re-open and tag me if you wish me to commit the script to the DataPort-Examples!

**Comment by SMock123** [comment]
@levaphenyl  I've added a reference to our readme pointing at your conversion script that's in https://github.com/nilmtk/nilmtk . Have a look, let me know if you would like more direct attribution yourself. I'm happy to do so. Thanks again!

**Comment by levaphenyl** [comment]
Looks good to me! Thank you, @SMock123  :)
